### ISSUE TITLE
"Space named [stack] already exists!" on Ghidra 9.1.2

### ISSUE THREAD

**Issue by fmagin** [Comsecuris/gdbghidra#8]
On https://github.com/NationalSecurityAgency/ghidra/tree/adedcde30f893fe3f48291f15866aed05df04fc9 (newest commit as of the time of this issue being opened) the plugin crashes when the gdb client sends the stack information:

```
Uncaught Exception! 
RuntimeException - ghidra.util.exception.DuplicateNameException: Space named [stack] already exists!
java.lang.RuntimeException: ghidra.util.exception.DuplicateNameException: Space named [stack] already exists!
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:303)
	at gdbghidra.events.MemoryEvent.handleEvent(MemoryEvent.java:104)
	at gdbghidra.GDBReceiver.handleConnection(GDBReceiver.java:134)
	at gdbghidra.GDBReceiver.run(GDBReceiver.java:79)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: ghidra.util.exception.DuplicateNameException: Space named [stack] already exists!
	at ghidra.program.model.address.DefaultAddressFactory.addAddressSpace(DefaultAddressFactory.java:380)
	at ghidra.program.database.ProgramAddressFactory.addOverlayAddressSpace(ProgramAddressFactory.java:113)
	at ghidra.program.database.ProgramDB.addOverlaySpace(ProgramDB.java:1325)
	at ghidra.program.database.mem.MemoryMapDB.createOverlaySpace(MemoryMapDB.java:469)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:490)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:298)
	... 4 more

```

**Comment by F-Lehmann** [comment]
same problem in 9.1.2

**Comment by fmagin** [comment]
I guess they just included whatever is causing this issue in 9.1.2 (which was released 2 Months after that bug was present in master).
Changed the title to make it clear that this an issue with the current release
